// Code generated by protoc-gen-go. DO NOT EDIT.
// source: smrpc.proto

package smrpc

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type FilesystemTrimRequest struct {
	IsEncryptedDevice    bool     `protobuf:"varint,1,opt,name=is_encrypted_device,json=isEncryptedDevice,proto3" json:"is_encrypted_device,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FilesystemTrimRequest) Reset()         { *m = FilesystemTrimRequest{} }
func (m *FilesystemTrimRequest) String() string { return proto.CompactTextString(m) }
func (*FilesystemTrimRequest) ProtoMessage()    {}
func (*FilesystemTrimRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_754d325a94992d5d, []int{0}
}

func (m *FilesystemTrimRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FilesystemTrimRequest.Unmarshal(m, b)
}
func (m *FilesystemTrimRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FilesystemTrimRequest.Marshal(b, m, deterministic)
}
func (m *FilesystemTrimRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FilesystemTrimRequest.Merge(m, src)
}
func (m *FilesystemTrimRequest) XXX_Size() int {
	return xxx_messageInfo_FilesystemTrimRequest.Size(m)
}
func (m *FilesystemTrimRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FilesystemTrimRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FilesystemTrimRequest proto.InternalMessageInfo

func (m *FilesystemTrimRequest) GetIsEncryptedDevice() bool {
	if m != nil {
		return m.IsEncryptedDevice
	}
	return false
}

type FilesystemMountStatusResponse struct {
	State                string   `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	Error                string   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FilesystemMountStatusResponse) Reset()         { *m = FilesystemMountStatusResponse{} }
func (m *FilesystemMountStatusResponse) String() string { return proto.CompactTextString(m) }
func (*FilesystemMountStatusResponse) ProtoMessage()    {}
func (*FilesystemMountStatusResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_754d325a94992d5d, []int{1}
}

func (m *FilesystemMountStatusResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FilesystemMountStatusResponse.Unmarshal(m, b)
}
func (m *FilesystemMountStatusResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FilesystemMountStatusResponse.Marshal(b, m, deterministic)
}
func (m *FilesystemMountStatusResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FilesystemMountStatusResponse.Merge(m, src)
}
func (m *FilesystemMountStatusResponse) XXX_Size() int {
	return xxx_messageInfo_FilesystemMountStatusResponse.Size(m)
}
func (m *FilesystemMountStatusResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FilesystemMountStatusResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FilesystemMountStatusResponse proto.InternalMessageInfo

func (m *FilesystemMountStatusResponse) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

func (m *FilesystemMountStatusResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func init() {
	proto.RegisterType((*FilesystemTrimRequest)(nil), "FilesystemTrimRequest")
	proto.RegisterType((*FilesystemMountStatusResponse)(nil), "FilesystemMountStatusResponse")
}

func init() { proto.RegisterFile("smrpc.proto", fileDescriptor_754d325a94992d5d) }

var fileDescriptor_754d325a94992d5d = []byte{
	// 249 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x90, 0x41, 0x4b, 0xc3, 0x40,
	0x10, 0x85, 0x1b, 0x41, 0xd1, 0x11, 0x14, 0xb7, 0x5a, 0x4a, 0x45, 0x91, 0x9c, 0x3c, 0x6d, 0x41,
	0xff, 0x81, 0x5a, 0x3d, 0x48, 0x0f, 0x26, 0xde, 0xcb, 0x36, 0x1d, 0xe3, 0x42, 0x93, 0x5d, 0x67,
	0x26, 0x42, 0x7e, 0xb6, 0xff, 0x40, 0x92, 0xa5, 0x18, 0xc5, 0xf4, 0xf8, 0xde, 0x83, 0x37, 0xf3,
	0x3d, 0x38, 0xe4, 0x82, 0x7c, 0xa6, 0x3d, 0x39, 0x71, 0x93, 0xf3, 0xdc, 0xb9, 0x7c, 0x8d, 0xd3,
	0x56, 0x2d, 0xab, 0xb7, 0x29, 0x16, 0x5e, 0xea, 0x10, 0xc6, 0x4f, 0x70, 0xf6, 0x68, 0xd7, 0xc8,
	0x35, 0x0b, 0x16, 0xaf, 0x64, 0x8b, 0x04, 0x3f, 0x2a, 0x64, 0x51, 0x1a, 0x86, 0x96, 0x17, 0x58,
	0x66, 0x54, 0x7b, 0xc1, 0xd5, 0x62, 0x85, 0x9f, 0x36, 0xc3, 0x71, 0x74, 0x15, 0x5d, 0xef, 0x27,
	0x27, 0x96, 0x67, 0x9b, 0xe4, 0xa1, 0x0d, 0xe2, 0x67, 0xb8, 0xf8, 0x29, 0x9a, 0xbb, 0xaa, 0x94,
	0x54, 0x8c, 0x54, 0x9c, 0x20, 0x7b, 0x57, 0x32, 0xaa, 0x53, 0xd8, 0x65, 0x31, 0x12, 0x2a, 0x0e,
	0x92, 0x20, 0x1a, 0x17, 0x89, 0x1c, 0x8d, 0x77, 0x82, 0xdb, 0x8a, 0x9b, 0xaf, 0x08, 0x86, 0xe9,
	0xbb, 0x21, 0x9c, 0x9b, 0xd2, 0xe4, 0x48, 0x29, 0x52, 0x73, 0x44, 0xdd, 0xc3, 0xf1, 0x9f, 0x23,
	0x6a, 0xa4, 0x03, 0x9e, 0xde, 0xe0, 0xe9, 0x59, 0x83, 0x37, 0xe9, 0xf1, 0xe3, 0x81, 0x7a, 0xe9,
	0x22, 0x77, 0x3e, 0xed, 0xad, 0xba, 0xd4, 0x5b, 0xc9, 0xe2, 0x81, 0xba, 0x83, 0xa3, 0xdf, 0x2b,
	0xaa, 0x91, 0xfe, 0x77, 0xd6, 0xfe, 0xb7, 0x96, 0x7b, 0xad, 0x73, 0xfb, 0x1d, 0x00, 0x00, 0xff,
	0xff, 0x91, 0x5e, 0x26, 0x93, 0xbc, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ShareManagerServiceClient is the client API for ShareManagerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ShareManagerServiceClient interface {
	FilesystemMount(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*empty.Empty, error)
	FilesystemMountStatus(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*FilesystemMountStatusResponse, error)
	FilesystemTrim(ctx context.Context, in *FilesystemTrimRequest, opts ...grpc.CallOption) (*empty.Empty, error)
}

type shareManagerServiceClient struct {
	cc *grpc.ClientConn
}

func NewShareManagerServiceClient(cc *grpc.ClientConn) ShareManagerServiceClient {
	return &shareManagerServiceClient{cc}
}

func (c *shareManagerServiceClient) FilesystemMount(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/ShareManagerService/FilesystemMount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shareManagerServiceClient) FilesystemMountStatus(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*FilesystemMountStatusResponse, error) {
	out := new(FilesystemMountStatusResponse)
	err := c.cc.Invoke(ctx, "/ShareManagerService/FilesystemMountStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shareManagerServiceClient) FilesystemTrim(ctx context.Context, in *FilesystemTrimRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/ShareManagerService/FilesystemTrim", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ShareManagerServiceServer is the server API for ShareManagerService service.
type ShareManagerServiceServer interface {
	FilesystemMount(context.Context, *empty.Empty) (*empty.Empty, error)
	FilesystemMountStatus(context.Context, *empty.Empty) (*FilesystemMountStatusResponse, error)
	FilesystemTrim(context.Context, *FilesystemTrimRequest) (*empty.Empty, error)
}

// UnimplementedShareManagerServiceServer can be embedded to have forward compatible implementations.
type UnimplementedShareManagerServiceServer struct {
}

func (*UnimplementedShareManagerServiceServer) FilesystemMount(ctx context.Context, req *empty.Empty) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FilesystemMount not implemented")
}
func (*UnimplementedShareManagerServiceServer) FilesystemMountStatus(ctx context.Context, req *empty.Empty) (*FilesystemMountStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FilesystemMountStatus not implemented")
}
func (*UnimplementedShareManagerServiceServer) FilesystemTrim(ctx context.Context, req *FilesystemTrimRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FilesystemTrim not implemented")
}

func RegisterShareManagerServiceServer(s *grpc.Server, srv ShareManagerServiceServer) {
	s.RegisterService(&_ShareManagerService_serviceDesc, srv)
}

func _ShareManagerService_FilesystemMount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShareManagerServiceServer).FilesystemMount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ShareManagerService/FilesystemMount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShareManagerServiceServer).FilesystemMount(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShareManagerService_FilesystemMountStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShareManagerServiceServer).FilesystemMountStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ShareManagerService/FilesystemMountStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShareManagerServiceServer).FilesystemMountStatus(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShareManagerService_FilesystemTrim_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FilesystemTrimRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShareManagerServiceServer).FilesystemTrim(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ShareManagerService/FilesystemTrim",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShareManagerServiceServer).FilesystemTrim(ctx, req.(*FilesystemTrimRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ShareManagerService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ShareManagerService",
	HandlerType: (*ShareManagerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FilesystemMount",
			Handler:    _ShareManagerService_FilesystemMount_Handler,
		},
		{
			MethodName: "FilesystemMountStatus",
			Handler:    _ShareManagerService_FilesystemMountStatus_Handler,
		},
		{
			MethodName: "FilesystemTrim",
			Handler:    _ShareManagerService_FilesystemTrim_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "smrpc.proto",
}
